rpcType: "http"
metaStorageDirectory: ""

selfEndpoint:
  nodeId: node1
  ip: "127.0.0.1"
  port: 8081

peerEndpoints:
  - nodeId: node2
    ip: "127.0.0.1"
    port: 8082
  - nodeId: node3
    ip: "127.0.0.1"
    port: 8083


raftConfigurations:
  pingTimeoutMs: 2000
  electionTimeoutMs: 5000
