rpcType: "http"

selfEndpoint:
  ip: "127.0.0.1"
  port: 8082

peerEndpoints:
  - ip: "127.0.0.1"
    port: 8083
  - ip: "127.0.0.1"
    port: 8081


raftConfigurations:
  pingTimeoutMs: 2000
  electionTimeoutMs: 5000
