// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface BatchLogEntriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.BatchLogEntries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.ylgrgyq.replicator.proto.LogEntry entries = 1;</code>
   */
  java.util.List<com.github.ylgrgyq.replicator.proto.LogEntry> 
      getEntriesList();
  /**
   * <code>repeated .com.github.ylgrgyq.replicator.proto.LogEntry entries = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.LogEntry getEntries(int index);
  /**
   * <code>repeated .com.github.ylgrgyq.replicator.proto.LogEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .com.github.ylgrgyq.replicator.proto.LogEntry entries = 1;</code>
   */
  java.util.List<? extends com.github.ylgrgyq.replicator.proto.LogEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .com.github.ylgrgyq.replicator.proto.LogEntry entries = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.LogEntryOrBuilder getEntriesOrBuilder(
      int index);
}
