// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ylgrgyq_replicator_proto_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ylgrgyq_replicator_proto_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ylgrgyq_replicator_proto_Snapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ylgrgyq_replicator_proto_Snapshot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016commands.proto\022#com.github.ylgrgyq.rep" +
      "licator.proto\"$\n\010LogEntry\022\n\n\002id\030\001 \001(\003\022\014\n" +
      "\004data\030\003 \001(\014\"$\n\010Snapshot\022\n\n\002id\030\001 \001(\003\022\014\n\004d" +
      "ata\030\002 \001(\014B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_ylgrgyq_replicator_proto_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_ylgrgyq_replicator_proto_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ylgrgyq_replicator_proto_LogEntry_descriptor,
        new java.lang.String[] { "Id", "Data", });
    internal_static_com_github_ylgrgyq_replicator_proto_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_ylgrgyq_replicator_proto_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ylgrgyq_replicator_proto_Snapshot_descriptor,
        new java.lang.String[] { "Id", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
