// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

/**
 * Protobuf enum {@code com.github.ylgrgyq.replicator.proto.CommandType}
 */
public enum CommandType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>HANDSHAKE = 1;</code>
   */
  HANDSHAKE(1),
  /**
   * <code>FETCH_LOGS = 2;</code>
   */
  FETCH_LOGS(2),
  /**
   * <code>FETCH_SNAPSHOT = 3;</code>
   */
  FETCH_SNAPSHOT(3),
  /**
   * <code>ERROR = 4;</code>
   */
  ERROR(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>HANDSHAKE = 1;</code>
   */
  public static final int HANDSHAKE_VALUE = 1;
  /**
   * <code>FETCH_LOGS = 2;</code>
   */
  public static final int FETCH_LOGS_VALUE = 2;
  /**
   * <code>FETCH_SNAPSHOT = 3;</code>
   */
  public static final int FETCH_SNAPSHOT_VALUE = 3;
  /**
   * <code>ERROR = 4;</code>
   */
  public static final int ERROR_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommandType valueOf(int value) {
    return forNumber(value);
  }

  public static CommandType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return HANDSHAKE;
      case 2: return FETCH_LOGS;
      case 3: return FETCH_SNAPSHOT;
      case 4: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommandType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
          public CommandType findValueByNumber(int number) {
            return CommandType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.ylgrgyq.replicator.proto.Commands.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final CommandType[] VALUES = values();

  public static CommandType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CommandType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.ylgrgyq.replicator.proto.CommandType)
}

