// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  boolean hasError();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.ErrorInfo getError();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder getErrorOrBuilder();
}
