// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.replicator.proto.Error}
 */
public  final class Error extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.replicator.proto.Error)
    ErrorOrBuilder {
  // Use Error.newBuilder() to construct.
  private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Error() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Error(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.github.ylgrgyq.replicator.proto.ErrorInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_Error_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_Error_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.replicator.proto.Error.class, com.github.ylgrgyq.replicator.proto.Error.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private com.github.ylgrgyq.replicator.proto.ErrorInfo error_;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.ErrorInfo getError() {
    return error_ == null ? com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.replicator.proto.Error)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.replicator.proto.Error other = (com.github.ylgrgyq.replicator.proto.Error) obj;

    boolean result = true;
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.replicator.proto.Error prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.replicator.proto.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.replicator.proto.Error)
      com.github.ylgrgyq.replicator.proto.ErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_Error_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.replicator.proto.Error.class, com.github.ylgrgyq.replicator.proto.Error.Builder.class);
    }

    // Construct using com.github.ylgrgyq.replicator.proto.Error.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_Error_descriptor;
    }

    public com.github.ylgrgyq.replicator.proto.Error getDefaultInstanceForType() {
      return com.github.ylgrgyq.replicator.proto.Error.getDefaultInstance();
    }

    public com.github.ylgrgyq.replicator.proto.Error build() {
      com.github.ylgrgyq.replicator.proto.Error result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.replicator.proto.Error buildPartial() {
      com.github.ylgrgyq.replicator.proto.Error result = new com.github.ylgrgyq.replicator.proto.Error(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.replicator.proto.Error) {
        return mergeFrom((com.github.ylgrgyq.replicator.proto.Error)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.replicator.proto.Error other) {
      if (other == com.github.ylgrgyq.replicator.proto.Error.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.replicator.proto.Error parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.replicator.proto.Error) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.ylgrgyq.replicator.proto.ErrorInfo error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder> errorBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfo getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public Builder setError(com.github.ylgrgyq.replicator.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public Builder setError(
        com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public Builder mergeError(com.github.ylgrgyq.replicator.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.github.ylgrgyq.replicator.proto.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.replicator.proto.Error)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.replicator.proto.Error)
  private static final com.github.ylgrgyq.replicator.proto.Error DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.replicator.proto.Error();
  }

  public static com.github.ylgrgyq.replicator.proto.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Error>
      PARSER = new com.google.protobuf.AbstractParser<Error>() {
    public Error parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Error(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Error> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Error> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.replicator.proto.Error getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

