// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface FetchSnapshotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  boolean hasSnapshot();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.Snapshot getSnapshot();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder getSnapshotOrBuilder();
}
