// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface FetchLogsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.FetchLogsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 fromId = 1;</code>
   */
  long getFromId();

  /**
   * <code>optional int32 limit = 2;</code>
   */
  int getLimit();
}
