// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.replicator.proto.FetchLogsResponse}
 */
public  final class FetchLogsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.replicator.proto.FetchLogsResponse)
    FetchLogsResponseOrBuilder {
  // Use FetchLogsResponse.newBuilder() to construct.
  private FetchLogsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchLogsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchLogsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder subBuilder = null;
            if (logs_ != null) {
              subBuilder = logs_.toBuilder();
            }
            logs_ = input.readMessage(com.github.ylgrgyq.replicator.proto.BatchLogEntries.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(logs_);
              logs_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchLogsResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchLogsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.replicator.proto.FetchLogsResponse.class, com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder.class);
  }

  public static final int LOGS_FIELD_NUMBER = 1;
  private com.github.ylgrgyq.replicator.proto.BatchLogEntries logs_;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  public boolean hasLogs() {
    return logs_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.BatchLogEntries getLogs() {
    return logs_ == null ? com.github.ylgrgyq.replicator.proto.BatchLogEntries.getDefaultInstance() : logs_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder getLogsOrBuilder() {
    return getLogs();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (logs_ != null) {
      output.writeMessage(1, getLogs());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (logs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLogs());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.replicator.proto.FetchLogsResponse)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.replicator.proto.FetchLogsResponse other = (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) obj;

    boolean result = true;
    result = result && (hasLogs() == other.hasLogs());
    if (hasLogs()) {
      result = result && getLogs()
          .equals(other.getLogs());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasLogs()) {
      hash = (37 * hash) + LOGS_FIELD_NUMBER;
      hash = (53 * hash) + getLogs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.replicator.proto.FetchLogsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.replicator.proto.FetchLogsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.replicator.proto.FetchLogsResponse)
      com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchLogsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchLogsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.replicator.proto.FetchLogsResponse.class, com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder.class);
    }

    // Construct using com.github.ylgrgyq.replicator.proto.FetchLogsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (logsBuilder_ == null) {
        logs_ = null;
      } else {
        logs_ = null;
        logsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchLogsResponse_descriptor;
    }

    public com.github.ylgrgyq.replicator.proto.FetchLogsResponse getDefaultInstanceForType() {
      return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
    }

    public com.github.ylgrgyq.replicator.proto.FetchLogsResponse build() {
      com.github.ylgrgyq.replicator.proto.FetchLogsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.replicator.proto.FetchLogsResponse buildPartial() {
      com.github.ylgrgyq.replicator.proto.FetchLogsResponse result = new com.github.ylgrgyq.replicator.proto.FetchLogsResponse(this);
      if (logsBuilder_ == null) {
        result.logs_ = logs_;
      } else {
        result.logs_ = logsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.replicator.proto.FetchLogsResponse) {
        return mergeFrom((com.github.ylgrgyq.replicator.proto.FetchLogsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.replicator.proto.FetchLogsResponse other) {
      if (other == com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance()) return this;
      if (other.hasLogs()) {
        mergeLogs(other.getLogs());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.replicator.proto.FetchLogsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.ylgrgyq.replicator.proto.BatchLogEntries logs_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.BatchLogEntries, com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder, com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder> logsBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public boolean hasLogs() {
      return logsBuilder_ != null || logs_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.BatchLogEntries getLogs() {
      if (logsBuilder_ == null) {
        return logs_ == null ? com.github.ylgrgyq.replicator.proto.BatchLogEntries.getDefaultInstance() : logs_;
      } else {
        return logsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public Builder setLogs(com.github.ylgrgyq.replicator.proto.BatchLogEntries value) {
      if (logsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        logs_ = value;
        onChanged();
      } else {
        logsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public Builder setLogs(
        com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder builderForValue) {
      if (logsBuilder_ == null) {
        logs_ = builderForValue.build();
        onChanged();
      } else {
        logsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public Builder mergeLogs(com.github.ylgrgyq.replicator.proto.BatchLogEntries value) {
      if (logsBuilder_ == null) {
        if (logs_ != null) {
          logs_ =
            com.github.ylgrgyq.replicator.proto.BatchLogEntries.newBuilder(logs_).mergeFrom(value).buildPartial();
        } else {
          logs_ = value;
        }
        onChanged();
      } else {
        logsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public Builder clearLogs() {
      if (logsBuilder_ == null) {
        logs_ = null;
        onChanged();
      } else {
        logs_ = null;
        logsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder getLogsBuilder() {
      
      onChanged();
      return getLogsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder getLogsOrBuilder() {
      if (logsBuilder_ != null) {
        return logsBuilder_.getMessageOrBuilder();
      } else {
        return logs_ == null ?
            com.github.ylgrgyq.replicator.proto.BatchLogEntries.getDefaultInstance() : logs_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.BatchLogEntries, com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder, com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder> 
        getLogsFieldBuilder() {
      if (logsBuilder_ == null) {
        logsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.BatchLogEntries, com.github.ylgrgyq.replicator.proto.BatchLogEntries.Builder, com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder>(
                getLogs(),
                getParentForChildren(),
                isClean());
        logs_ = null;
      }
      return logsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.replicator.proto.FetchLogsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.replicator.proto.FetchLogsResponse)
  private static final com.github.ylgrgyq.replicator.proto.FetchLogsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.replicator.proto.FetchLogsResponse();
  }

  public static com.github.ylgrgyq.replicator.proto.FetchLogsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchLogsResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchLogsResponse>() {
    public FetchLogsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchLogsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchLogsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchLogsResponse> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.replicator.proto.FetchLogsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

