// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface FetchLogsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.FetchLogsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  boolean hasLogs();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.BatchLogEntries getLogs();
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.BatchLogEntries logs = 1;</code>
   */
  com.github.ylgrgyq.replicator.proto.BatchLogEntriesOrBuilder getLogsOrBuilder();
}
