// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse}
 */
public  final class FetchSnapshotResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)
    FetchSnapshotResponseOrBuilder {
  // Use FetchSnapshotResponse.newBuilder() to construct.
  private FetchSnapshotResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchSnapshotResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchSnapshotResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.ylgrgyq.replicator.proto.Snapshot.Builder subBuilder = null;
            if (snapshot_ != null) {
              subBuilder = snapshot_.toBuilder();
            }
            snapshot_ = input.readMessage(com.github.ylgrgyq.replicator.proto.Snapshot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(snapshot_);
              snapshot_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchSnapshotResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchSnapshotResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.class, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder.class);
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 1;
  private com.github.ylgrgyq.replicator.proto.Snapshot snapshot_;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  public boolean hasSnapshot() {
    return snapshot_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.Snapshot getSnapshot() {
    return snapshot_ == null ? com.github.ylgrgyq.replicator.proto.Snapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
   */
  public com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
    return getSnapshot();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (snapshot_ != null) {
      output.writeMessage(1, getSnapshot());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (snapshot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSnapshot());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse other = (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) obj;

    boolean result = true;
    result = result && (hasSnapshot() == other.hasSnapshot());
    if (hasSnapshot()) {
      result = result && getSnapshot()
          .equals(other.getSnapshot());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasSnapshot()) {
      hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshot().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)
      com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchSnapshotResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchSnapshotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.class, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder.class);
    }

    // Construct using com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (snapshotBuilder_ == null) {
        snapshot_ = null;
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_FetchSnapshotResponse_descriptor;
    }

    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse getDefaultInstanceForType() {
      return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
    }

    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse build() {
      com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse buildPartial() {
      com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse result = new com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse(this);
      if (snapshotBuilder_ == null) {
        result.snapshot_ = snapshot_;
      } else {
        result.snapshot_ = snapshotBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) {
        return mergeFrom((com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse other) {
      if (other == com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance()) return this;
      if (other.hasSnapshot()) {
        mergeSnapshot(other.getSnapshot());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.ylgrgyq.replicator.proto.Snapshot snapshot_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.Snapshot, com.github.ylgrgyq.replicator.proto.Snapshot.Builder, com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder> snapshotBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public boolean hasSnapshot() {
      return snapshotBuilder_ != null || snapshot_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.Snapshot getSnapshot() {
      if (snapshotBuilder_ == null) {
        return snapshot_ == null ? com.github.ylgrgyq.replicator.proto.Snapshot.getDefaultInstance() : snapshot_;
      } else {
        return snapshotBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public Builder setSnapshot(com.github.ylgrgyq.replicator.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snapshot_ = value;
        onChanged();
      } else {
        snapshotBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public Builder setSnapshot(
        com.github.ylgrgyq.replicator.proto.Snapshot.Builder builderForValue) {
      if (snapshotBuilder_ == null) {
        snapshot_ = builderForValue.build();
        onChanged();
      } else {
        snapshotBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public Builder mergeSnapshot(com.github.ylgrgyq.replicator.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (snapshot_ != null) {
          snapshot_ =
            com.github.ylgrgyq.replicator.proto.Snapshot.newBuilder(snapshot_).mergeFrom(value).buildPartial();
        } else {
          snapshot_ = value;
        }
        onChanged();
      } else {
        snapshotBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public Builder clearSnapshot() {
      if (snapshotBuilder_ == null) {
        snapshot_ = null;
        onChanged();
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.Snapshot.Builder getSnapshotBuilder() {
      
      onChanged();
      return getSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    public com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
      if (snapshotBuilder_ != null) {
        return snapshotBuilder_.getMessageOrBuilder();
      } else {
        return snapshot_ == null ?
            com.github.ylgrgyq.replicator.proto.Snapshot.getDefaultInstance() : snapshot_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.Snapshot snapshot = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.Snapshot, com.github.ylgrgyq.replicator.proto.Snapshot.Builder, com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder> 
        getSnapshotFieldBuilder() {
      if (snapshotBuilder_ == null) {
        snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.Snapshot, com.github.ylgrgyq.replicator.proto.Snapshot.Builder, com.github.ylgrgyq.replicator.proto.SnapshotOrBuilder>(
                getSnapshot(),
                getParentForChildren(),
                isClean());
        snapshot_ = null;
      }
      return snapshotBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse)
  private static final com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse();
  }

  public static com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchSnapshotResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchSnapshotResponse>() {
    public FetchSnapshotResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchSnapshotResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchSnapshotResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchSnapshotResponse> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

