// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface HandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.replicator.proto.HandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string topic = 1;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>optional string topic = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
