// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.replicator.proto.ReplicatorCommand}
 */
public  final class ReplicatorCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.replicator.proto.ReplicatorCommand)
    ReplicatorCommandOrBuilder {
  // Use ReplicatorCommand.newBuilder() to construct.
  private ReplicatorCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplicatorCommand() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReplicatorCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 26: {
            com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.HandshakeRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder subBuilder = null;
            if (requestCase_ == 4) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.FetchLogsRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 4;
            break;
          }
          case 42: {
            com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder subBuilder = null;
            if (requestCase_ == 5) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 5;
            break;
          }
          case 50: {
            com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder subBuilder = null;
            if (responseCase_ == 6) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.HandshakeResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 6;
            break;
          }
          case 58: {
            com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder subBuilder = null;
            if (responseCase_ == 7) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.FetchLogsResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 7;
            break;
          }
          case 66: {
            com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder subBuilder = null;
            if (responseCase_ == 8) {
              subBuilder = ((com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 8;
            break;
          }
          case 74: {
            com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.github.ylgrgyq.replicator.proto.ErrorInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_ReplicatorCommand_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_ReplicatorCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.replicator.proto.ReplicatorCommand.class, com.github.ylgrgyq.replicator.proto.ReplicatorCommand.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite {
    HANDSHAKE_REQUEST(3),
    FETCH_LOGS_REQUEST(4),
    FETCH_SNAPSHOT_REQUEST(5),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 3: return HANDSHAKE_REQUEST;
        case 4: return FETCH_LOGS_REQUEST;
        case 5: return FETCH_SNAPSHOT_REQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite {
    HANDSHAKE_RESPONSE(6),
    FETCH_LOGS_RESPONSE(7),
    FETCH_SNAPSHOT_RESPONSE(8),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 6: return HANDSHAKE_RESPONSE;
        case 7: return FETCH_LOGS_RESPONSE;
        case 8: return FETCH_SNAPSHOT_RESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int HANDSHAKE_REQUEST_FIELD_NUMBER = 3;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
   */
  public com.github.ylgrgyq.replicator.proto.HandshakeRequest getHandshakeRequest() {
    if (requestCase_ == 3) {
       return (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
   */
  public com.github.ylgrgyq.replicator.proto.HandshakeRequestOrBuilder getHandshakeRequestOrBuilder() {
    if (requestCase_ == 3) {
       return (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
  }

  public static final int FETCH_LOGS_REQUEST_FIELD_NUMBER = 4;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchLogsRequest getFetchLogsRequest() {
    if (requestCase_ == 4) {
       return (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchLogsRequestOrBuilder getFetchLogsRequestOrBuilder() {
    if (requestCase_ == 4) {
       return (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
  }

  public static final int FETCH_SNAPSHOT_REQUEST_FIELD_NUMBER = 5;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest getFetchSnapshotRequest() {
    if (requestCase_ == 5) {
       return (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchSnapshotRequestOrBuilder getFetchSnapshotRequestOrBuilder() {
    if (requestCase_ == 5) {
       return (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
  }

  public static final int HANDSHAKE_RESPONSE_FIELD_NUMBER = 6;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
   */
  public com.github.ylgrgyq.replicator.proto.HandshakeResponse getHandshakeResponse() {
    if (responseCase_ == 6) {
       return (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
   */
  public com.github.ylgrgyq.replicator.proto.HandshakeResponseOrBuilder getHandshakeResponseOrBuilder() {
    if (responseCase_ == 6) {
       return (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
  }

  public static final int FETCH_LOGS_RESPONSE_FIELD_NUMBER = 7;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchLogsResponse getFetchLogsResponse() {
    if (responseCase_ == 7) {
       return (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder getFetchLogsResponseOrBuilder() {
    if (responseCase_ == 7) {
       return (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
  }

  public static final int FETCH_SNAPSHOT_RESPONSE_FIELD_NUMBER = 8;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse getFetchSnapshotResponse() {
    if (responseCase_ == 8) {
       return (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
   */
  public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder getFetchSnapshotResponseOrBuilder() {
    if (responseCase_ == 8) {
       return (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_;
    }
    return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
  }

  public static final int ERROR_FIELD_NUMBER = 9;
  private com.github.ylgrgyq.replicator.proto.ErrorInfo error_;
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
   */
  public com.github.ylgrgyq.replicator.proto.ErrorInfo getError() {
    return error_ == null ? com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
   */
  public com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 3) {
      output.writeMessage(3, (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_);
    }
    if (requestCase_ == 5) {
      output.writeMessage(5, (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_);
    }
    if (responseCase_ == 6) {
      output.writeMessage(6, (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_);
    }
    if (responseCase_ == 7) {
      output.writeMessage(7, (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_);
    }
    if (responseCase_ == 8) {
      output.writeMessage(8, (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_);
    }
    if (error_ != null) {
      output.writeMessage(9, getError());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_);
    }
    if (requestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_);
    }
    if (responseCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_);
    }
    if (responseCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_);
    }
    if (responseCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_);
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getError());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.replicator.proto.ReplicatorCommand)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.replicator.proto.ReplicatorCommand other = (com.github.ylgrgyq.replicator.proto.ReplicatorCommand) obj;

    boolean result = true;
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && getRequestCase().equals(
        other.getRequestCase());
    if (!result) return false;
    switch (requestCase_) {
      case 3:
        result = result && getHandshakeRequest()
            .equals(other.getHandshakeRequest());
        break;
      case 4:
        result = result && getFetchLogsRequest()
            .equals(other.getFetchLogsRequest());
        break;
      case 5:
        result = result && getFetchSnapshotRequest()
            .equals(other.getFetchSnapshotRequest());
        break;
      case 0:
      default:
    }
    result = result && getResponseCase().equals(
        other.getResponseCase());
    if (!result) return false;
    switch (responseCase_) {
      case 6:
        result = result && getHandshakeResponse()
            .equals(other.getHandshakeResponse());
        break;
      case 7:
        result = result && getFetchLogsResponse()
            .equals(other.getFetchLogsResponse());
        break;
      case 8:
        result = result && getFetchSnapshotResponse()
            .equals(other.getFetchSnapshotResponse());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    switch (requestCase_) {
      case 3:
        hash = (37 * hash) + HANDSHAKE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + FETCH_LOGS_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getFetchLogsRequest().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FETCH_SNAPSHOT_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getFetchSnapshotRequest().hashCode();
        break;
      case 0:
      default:
    }
    switch (responseCase_) {
      case 6:
        hash = (37 * hash) + HANDSHAKE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeResponse().hashCode();
        break;
      case 7:
        hash = (37 * hash) + FETCH_LOGS_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getFetchLogsResponse().hashCode();
        break;
      case 8:
        hash = (37 * hash) + FETCH_SNAPSHOT_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getFetchSnapshotResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.replicator.proto.ReplicatorCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.replicator.proto.ReplicatorCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.replicator.proto.ReplicatorCommand)
      com.github.ylgrgyq.replicator.proto.ReplicatorCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_ReplicatorCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_ReplicatorCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.replicator.proto.ReplicatorCommand.class, com.github.ylgrgyq.replicator.proto.ReplicatorCommand.Builder.class);
    }

    // Construct using com.github.ylgrgyq.replicator.proto.ReplicatorCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      requestCase_ = 0;
      request_ = null;
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.replicator.proto.Commands.internal_static_com_github_ylgrgyq_replicator_proto_ReplicatorCommand_descriptor;
    }

    public com.github.ylgrgyq.replicator.proto.ReplicatorCommand getDefaultInstanceForType() {
      return com.github.ylgrgyq.replicator.proto.ReplicatorCommand.getDefaultInstance();
    }

    public com.github.ylgrgyq.replicator.proto.ReplicatorCommand build() {
      com.github.ylgrgyq.replicator.proto.ReplicatorCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.replicator.proto.ReplicatorCommand buildPartial() {
      com.github.ylgrgyq.replicator.proto.ReplicatorCommand result = new com.github.ylgrgyq.replicator.proto.ReplicatorCommand(this);
      if (requestCase_ == 3) {
        if (handshakeRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = handshakeRequestBuilder_.build();
        }
      }
      if (requestCase_ == 4) {
        if (fetchLogsRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = fetchLogsRequestBuilder_.build();
        }
      }
      if (requestCase_ == 5) {
        if (fetchSnapshotRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = fetchSnapshotRequestBuilder_.build();
        }
      }
      if (responseCase_ == 6) {
        if (handshakeResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = handshakeResponseBuilder_.build();
        }
      }
      if (responseCase_ == 7) {
        if (fetchLogsResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = fetchLogsResponseBuilder_.build();
        }
      }
      if (responseCase_ == 8) {
        if (fetchSnapshotResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = fetchSnapshotResponseBuilder_.build();
        }
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.requestCase_ = requestCase_;
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.replicator.proto.ReplicatorCommand) {
        return mergeFrom((com.github.ylgrgyq.replicator.proto.ReplicatorCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.replicator.proto.ReplicatorCommand other) {
      if (other == com.github.ylgrgyq.replicator.proto.ReplicatorCommand.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      switch (other.getRequestCase()) {
        case HANDSHAKE_REQUEST: {
          mergeHandshakeRequest(other.getHandshakeRequest());
          break;
        }
        case FETCH_LOGS_REQUEST: {
          mergeFetchLogsRequest(other.getFetchLogsRequest());
          break;
        }
        case FETCH_SNAPSHOT_REQUEST: {
          mergeFetchSnapshotRequest(other.getFetchSnapshotRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      switch (other.getResponseCase()) {
        case HANDSHAKE_RESPONSE: {
          mergeHandshakeResponse(other.getHandshakeResponse());
          break;
        }
        case FETCH_LOGS_RESPONSE: {
          mergeFetchLogsResponse(other.getFetchLogsResponse());
          break;
        }
        case FETCH_SNAPSHOT_RESPONSE: {
          mergeFetchSnapshotResponse(other.getFetchSnapshotResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.replicator.proto.ReplicatorCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.replicator.proto.ReplicatorCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.HandshakeRequest, com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder, com.github.ylgrgyq.replicator.proto.HandshakeRequestOrBuilder> handshakeRequestBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeRequest getHandshakeRequest() {
      if (handshakeRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return handshakeRequestBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public Builder setHandshakeRequest(com.github.ylgrgyq.replicator.proto.HandshakeRequest value) {
      if (handshakeRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        handshakeRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public Builder setHandshakeRequest(
        com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder builderForValue) {
      if (handshakeRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        handshakeRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public Builder mergeHandshakeRequest(com.github.ylgrgyq.replicator.proto.HandshakeRequest value) {
      if (handshakeRequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance()) {
          request_ = com.github.ylgrgyq.replicator.proto.HandshakeRequest.newBuilder((com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          handshakeRequestBuilder_.mergeFrom(value);
        }
        handshakeRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public Builder clearHandshakeRequest() {
      if (handshakeRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        handshakeRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder getHandshakeRequestBuilder() {
      return getHandshakeRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeRequestOrBuilder getHandshakeRequestOrBuilder() {
      if ((requestCase_ == 3) && (handshakeRequestBuilder_ != null)) {
        return handshakeRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeRequest handshake_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.HandshakeRequest, com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder, com.github.ylgrgyq.replicator.proto.HandshakeRequestOrBuilder> 
        getHandshakeRequestFieldBuilder() {
      if (handshakeRequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = com.github.ylgrgyq.replicator.proto.HandshakeRequest.getDefaultInstance();
        }
        handshakeRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.HandshakeRequest, com.github.ylgrgyq.replicator.proto.HandshakeRequest.Builder, com.github.ylgrgyq.replicator.proto.HandshakeRequestOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.HandshakeRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return handshakeRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchLogsRequest, com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsRequestOrBuilder> fetchLogsRequestBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsRequest getFetchLogsRequest() {
      if (fetchLogsRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          return (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return fetchLogsRequestBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public Builder setFetchLogsRequest(com.github.ylgrgyq.replicator.proto.FetchLogsRequest value) {
      if (fetchLogsRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        fetchLogsRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public Builder setFetchLogsRequest(
        com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder builderForValue) {
      if (fetchLogsRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        fetchLogsRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public Builder mergeFetchLogsRequest(com.github.ylgrgyq.replicator.proto.FetchLogsRequest value) {
      if (fetchLogsRequestBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance()) {
          request_ = com.github.ylgrgyq.replicator.proto.FetchLogsRequest.newBuilder((com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          fetchLogsRequestBuilder_.mergeFrom(value);
        }
        fetchLogsRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public Builder clearFetchLogsRequest() {
      if (fetchLogsRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        fetchLogsRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder getFetchLogsRequestBuilder() {
      return getFetchLogsRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsRequestOrBuilder getFetchLogsRequestOrBuilder() {
      if ((requestCase_ == 4) && (fetchLogsRequestBuilder_ != null)) {
        return fetchLogsRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsRequest fetch_logs_request = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchLogsRequest, com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsRequestOrBuilder> 
        getFetchLogsRequestFieldBuilder() {
      if (fetchLogsRequestBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = com.github.ylgrgyq.replicator.proto.FetchLogsRequest.getDefaultInstance();
        }
        fetchLogsRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.FetchLogsRequest, com.github.ylgrgyq.replicator.proto.FetchLogsRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsRequestOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.FetchLogsRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();;
      return fetchLogsRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequestOrBuilder> fetchSnapshotRequestBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest getFetchSnapshotRequest() {
      if (fetchSnapshotRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          return (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 5) {
          return fetchSnapshotRequestBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public Builder setFetchSnapshotRequest(com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest value) {
      if (fetchSnapshotRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        fetchSnapshotRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public Builder setFetchSnapshotRequest(
        com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder builderForValue) {
      if (fetchSnapshotRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        fetchSnapshotRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public Builder mergeFetchSnapshotRequest(com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest value) {
      if (fetchSnapshotRequestBuilder_ == null) {
        if (requestCase_ == 5 &&
            request_ != com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance()) {
          request_ = com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.newBuilder((com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 5) {
          fetchSnapshotRequestBuilder_.mergeFrom(value);
        }
        fetchSnapshotRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public Builder clearFetchSnapshotRequest() {
      if (fetchSnapshotRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
        }
        fetchSnapshotRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder getFetchSnapshotRequestBuilder() {
      return getFetchSnapshotRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotRequestOrBuilder getFetchSnapshotRequestOrBuilder() {
      if ((requestCase_ == 5) && (fetchSnapshotRequestBuilder_ != null)) {
        return fetchSnapshotRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 5) {
          return (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest fetch_snapshot_request = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequestOrBuilder> 
        getFetchSnapshotRequestFieldBuilder() {
      if (fetchSnapshotRequestBuilder_ == null) {
        if (!(requestCase_ == 5)) {
          request_ = com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.getDefaultInstance();
        }
        fetchSnapshotRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotRequestOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.FetchSnapshotRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 5;
      onChanged();;
      return fetchSnapshotRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.HandshakeResponse, com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder, com.github.ylgrgyq.replicator.proto.HandshakeResponseOrBuilder> handshakeResponseBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeResponse getHandshakeResponse() {
      if (handshakeResponseBuilder_ == null) {
        if (responseCase_ == 6) {
          return (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 6) {
          return handshakeResponseBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public Builder setHandshakeResponse(com.github.ylgrgyq.replicator.proto.HandshakeResponse value) {
      if (handshakeResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        handshakeResponseBuilder_.setMessage(value);
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public Builder setHandshakeResponse(
        com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder builderForValue) {
      if (handshakeResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        handshakeResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public Builder mergeHandshakeResponse(com.github.ylgrgyq.replicator.proto.HandshakeResponse value) {
      if (handshakeResponseBuilder_ == null) {
        if (responseCase_ == 6 &&
            response_ != com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance()) {
          response_ = com.github.ylgrgyq.replicator.proto.HandshakeResponse.newBuilder((com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 6) {
          handshakeResponseBuilder_.mergeFrom(value);
        }
        handshakeResponseBuilder_.setMessage(value);
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public Builder clearHandshakeResponse() {
      if (handshakeResponseBuilder_ == null) {
        if (responseCase_ == 6) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 6) {
          responseCase_ = 0;
          response_ = null;
        }
        handshakeResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder getHandshakeResponseBuilder() {
      return getHandshakeResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    public com.github.ylgrgyq.replicator.proto.HandshakeResponseOrBuilder getHandshakeResponseOrBuilder() {
      if ((responseCase_ == 6) && (handshakeResponseBuilder_ != null)) {
        return handshakeResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 6) {
          return (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.HandshakeResponse handshake_response = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.HandshakeResponse, com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder, com.github.ylgrgyq.replicator.proto.HandshakeResponseOrBuilder> 
        getHandshakeResponseFieldBuilder() {
      if (handshakeResponseBuilder_ == null) {
        if (!(responseCase_ == 6)) {
          response_ = com.github.ylgrgyq.replicator.proto.HandshakeResponse.getDefaultInstance();
        }
        handshakeResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.HandshakeResponse, com.github.ylgrgyq.replicator.proto.HandshakeResponse.Builder, com.github.ylgrgyq.replicator.proto.HandshakeResponseOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.HandshakeResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 6;
      onChanged();;
      return handshakeResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchLogsResponse, com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder> fetchLogsResponseBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsResponse getFetchLogsResponse() {
      if (fetchLogsResponseBuilder_ == null) {
        if (responseCase_ == 7) {
          return (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 7) {
          return fetchLogsResponseBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public Builder setFetchLogsResponse(com.github.ylgrgyq.replicator.proto.FetchLogsResponse value) {
      if (fetchLogsResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        fetchLogsResponseBuilder_.setMessage(value);
      }
      responseCase_ = 7;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public Builder setFetchLogsResponse(
        com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder builderForValue) {
      if (fetchLogsResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        fetchLogsResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 7;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public Builder mergeFetchLogsResponse(com.github.ylgrgyq.replicator.proto.FetchLogsResponse value) {
      if (fetchLogsResponseBuilder_ == null) {
        if (responseCase_ == 7 &&
            response_ != com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance()) {
          response_ = com.github.ylgrgyq.replicator.proto.FetchLogsResponse.newBuilder((com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 7) {
          fetchLogsResponseBuilder_.mergeFrom(value);
        }
        fetchLogsResponseBuilder_.setMessage(value);
      }
      responseCase_ = 7;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public Builder clearFetchLogsResponse() {
      if (fetchLogsResponseBuilder_ == null) {
        if (responseCase_ == 7) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 7) {
          responseCase_ = 0;
          response_ = null;
        }
        fetchLogsResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder getFetchLogsResponseBuilder() {
      return getFetchLogsResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder getFetchLogsResponseOrBuilder() {
      if ((responseCase_ == 7) && (fetchLogsResponseBuilder_ != null)) {
        return fetchLogsResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 7) {
          return (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchLogsResponse fetch_logs_response = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchLogsResponse, com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder> 
        getFetchLogsResponseFieldBuilder() {
      if (fetchLogsResponseBuilder_ == null) {
        if (!(responseCase_ == 7)) {
          response_ = com.github.ylgrgyq.replicator.proto.FetchLogsResponse.getDefaultInstance();
        }
        fetchLogsResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.FetchLogsResponse, com.github.ylgrgyq.replicator.proto.FetchLogsResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchLogsResponseOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.FetchLogsResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 7;
      onChanged();;
      return fetchLogsResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder> fetchSnapshotResponseBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse getFetchSnapshotResponse() {
      if (fetchSnapshotResponseBuilder_ == null) {
        if (responseCase_ == 8) {
          return (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 8) {
          return fetchSnapshotResponseBuilder_.getMessage();
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public Builder setFetchSnapshotResponse(com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse value) {
      if (fetchSnapshotResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        fetchSnapshotResponseBuilder_.setMessage(value);
      }
      responseCase_ = 8;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public Builder setFetchSnapshotResponse(
        com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder builderForValue) {
      if (fetchSnapshotResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        fetchSnapshotResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 8;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public Builder mergeFetchSnapshotResponse(com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse value) {
      if (fetchSnapshotResponseBuilder_ == null) {
        if (responseCase_ == 8 &&
            response_ != com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance()) {
          response_ = com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.newBuilder((com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 8) {
          fetchSnapshotResponseBuilder_.mergeFrom(value);
        }
        fetchSnapshotResponseBuilder_.setMessage(value);
      }
      responseCase_ = 8;
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public Builder clearFetchSnapshotResponse() {
      if (fetchSnapshotResponseBuilder_ == null) {
        if (responseCase_ == 8) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 8) {
          responseCase_ = 0;
          response_ = null;
        }
        fetchSnapshotResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder getFetchSnapshotResponseBuilder() {
      return getFetchSnapshotResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    public com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder getFetchSnapshotResponseOrBuilder() {
      if ((responseCase_ == 8) && (fetchSnapshotResponseBuilder_ != null)) {
        return fetchSnapshotResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 8) {
          return (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_;
        }
        return com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse fetch_snapshot_response = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder> 
        getFetchSnapshotResponseFieldBuilder() {
      if (fetchSnapshotResponseBuilder_ == null) {
        if (!(responseCase_ == 8)) {
          response_ = com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.getDefaultInstance();
        }
        fetchSnapshotResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse.Builder, com.github.ylgrgyq.replicator.proto.FetchSnapshotResponseOrBuilder>(
                (com.github.ylgrgyq.replicator.proto.FetchSnapshotResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 8;
      onChanged();;
      return fetchSnapshotResponseBuilder_;
    }

    private com.github.ylgrgyq.replicator.proto.ErrorInfo error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder> errorBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfo getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public Builder setError(com.github.ylgrgyq.replicator.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public Builder setError(
        com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public Builder mergeError(com.github.ylgrgyq.replicator.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.github.ylgrgyq.replicator.proto.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    public com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.github.ylgrgyq.replicator.proto.ErrorInfo.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.replicator.proto.ErrorInfo error = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.replicator.proto.ErrorInfo, com.github.ylgrgyq.replicator.proto.ErrorInfo.Builder, com.github.ylgrgyq.replicator.proto.ErrorInfoOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.replicator.proto.ReplicatorCommand)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.replicator.proto.ReplicatorCommand)
  private static final com.github.ylgrgyq.replicator.proto.ReplicatorCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.replicator.proto.ReplicatorCommand();
  }

  public static com.github.ylgrgyq.replicator.proto.ReplicatorCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplicatorCommand>
      PARSER = new com.google.protobuf.AbstractParser<ReplicatorCommand>() {
    public ReplicatorCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplicatorCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplicatorCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplicatorCommand> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.replicator.proto.ReplicatorCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

