// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.replicator.proto;

public interface ReplicatorErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.proto.ReplicatorError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 error_code = 1;</code>
   */
  int getErrorCode();

  /**
   * <code>optional string error_msg = 2;</code>
   */
  String getErrorMsg();
  /**
   * <code>optional string error_msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();
}
