// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.proto;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ylgrgyq_proto_SyncLogEntries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_ylgrgyq_proto_Snapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_ylgrgyq_proto_Snapshot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016commands.proto\022\030com.github.ylgrgyq.pro" +
      "to\"A\n\016SyncLogEntries\022\022\n\nstartIndex\030\001 \001(\003" +
      "\022\r\n\005topic\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\"6\n\010Snapsho" +
      "t\022\014\n\004data\030\001 \001(\014\022\r\n\005index\030\002 \001(\003\022\r\n\005topic\030" +
      "\003 \001(\tB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_ylgrgyq_proto_SyncLogEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor,
        new java.lang.String[] { "StartIndex", "Topic", "Data", });
    internal_static_com_github_ylgrgyq_proto_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_ylgrgyq_proto_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_ylgrgyq_proto_Snapshot_descriptor,
        new java.lang.String[] { "Data", "Index", "Topic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
