// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.proto;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.proto.LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 index = 1;</code>
   */
  long getIndex();

  /**
   * <code>optional bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
