// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.proto.ReplicatorCommand}
 */
public  final class ReplicatorCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.proto.ReplicatorCommand)
    ReplicatorCommandOrBuilder {
  // Use ReplicatorCommand.newBuilder() to construct.
  private ReplicatorCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplicatorCommand() {
    type_ = 0;
    topic_ = "";
    fromIndex_ = 0L;
    limit_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReplicatorCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 24: {

            fromIndex_ = input.readInt64();
            break;
          }
          case 32: {

            limit_ = input.readInt32();
            break;
          }
          case 42: {
            com.github.ylgrgyq.proto.SyncLogEntries.Builder subBuilder = null;
            if (logs_ != null) {
              subBuilder = logs_.toBuilder();
            }
            logs_ = input.readMessage(com.github.ylgrgyq.proto.SyncLogEntries.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(logs_);
              logs_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.github.ylgrgyq.proto.Snapshot.Builder subBuilder = null;
            if (snapshot_ != null) {
              subBuilder = snapshot_.toBuilder();
            }
            snapshot_ = input.readMessage(com.github.ylgrgyq.proto.Snapshot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(snapshot_);
              snapshot_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.github.ylgrgyq.proto.ErrorInfo.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.github.ylgrgyq.proto.ErrorInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_ReplicatorCommand_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_ReplicatorCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.proto.ReplicatorCommand.class, com.github.ylgrgyq.proto.ReplicatorCommand.Builder.class);
  }

  /**
   * Protobuf enum {@code com.github.ylgrgyq.proto.ReplicatorCommand.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>GET = 1;</code>
     */
    GET(1),
    /**
     * <code>GET_RESP = 2;</code>
     */
    GET_RESP(2),
    /**
     * <code>SNAPSHOT = 3;</code>
     */
    SNAPSHOT(3),
    /**
     * <code>SNAPSHOT_RESP = 4;</code>
     */
    SNAPSHOT_RESP(4),
    /**
     * <code>ERROR = 5;</code>
     */
    ERROR(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>GET = 1;</code>
     */
    public static final int GET_VALUE = 1;
    /**
     * <code>GET_RESP = 2;</code>
     */
    public static final int GET_RESP_VALUE = 2;
    /**
     * <code>SNAPSHOT = 3;</code>
     */
    public static final int SNAPSHOT_VALUE = 3;
    /**
     * <code>SNAPSHOT_RESP = 4;</code>
     */
    public static final int SNAPSHOT_RESP_VALUE = 4;
    /**
     * <code>ERROR = 5;</code>
     */
    public static final int ERROR_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return GET;
        case 2: return GET_RESP;
        case 3: return SNAPSHOT;
        case 4: return SNAPSHOT_RESP;
        case 5: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.ylgrgyq.proto.ReplicatorCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.ylgrgyq.proto.ReplicatorCommand.CommandType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
   */
  public com.github.ylgrgyq.proto.ReplicatorCommand.CommandType getType() {
    com.github.ylgrgyq.proto.ReplicatorCommand.CommandType result = com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.valueOf(type_);
    return result == null ? com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.UNRECOGNIZED : result;
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private volatile java.lang.Object topic_;
  /**
   * <code>optional string topic = 2;</code>
   */
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>optional string topic = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMINDEX_FIELD_NUMBER = 3;
  private long fromIndex_;
  /**
   * <code>optional int64 fromIndex = 3;</code>
   */
  public long getFromIndex() {
    return fromIndex_;
  }

  public static final int LIMIT_FIELD_NUMBER = 4;
  private int limit_;
  /**
   * <code>optional int32 limit = 4;</code>
   */
  public int getLimit() {
    return limit_;
  }

  public static final int LOGS_FIELD_NUMBER = 5;
  private com.github.ylgrgyq.proto.SyncLogEntries logs_;
  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  public boolean hasLogs() {
    return logs_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  public com.github.ylgrgyq.proto.SyncLogEntries getLogs() {
    return logs_ == null ? com.github.ylgrgyq.proto.SyncLogEntries.getDefaultInstance() : logs_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  public com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder getLogsOrBuilder() {
    return getLogs();
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 6;
  private com.github.ylgrgyq.proto.Snapshot snapshot_;
  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  public boolean hasSnapshot() {
    return snapshot_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  public com.github.ylgrgyq.proto.Snapshot getSnapshot() {
    return snapshot_ == null ? com.github.ylgrgyq.proto.Snapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  public com.github.ylgrgyq.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
    return getSnapshot();
  }

  public static final int ERROR_FIELD_NUMBER = 7;
  private com.github.ylgrgyq.proto.ErrorInfo error_;
  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  public com.github.ylgrgyq.proto.ErrorInfo getError() {
    return error_ == null ? com.github.ylgrgyq.proto.ErrorInfo.getDefaultInstance() : error_;
  }
  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  public com.github.ylgrgyq.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
    }
    if (fromIndex_ != 0L) {
      output.writeInt64(3, fromIndex_);
    }
    if (limit_ != 0) {
      output.writeInt32(4, limit_);
    }
    if (logs_ != null) {
      output.writeMessage(5, getLogs());
    }
    if (snapshot_ != null) {
      output.writeMessage(6, getSnapshot());
    }
    if (error_ != null) {
      output.writeMessage(7, getError());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
    }
    if (fromIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, fromIndex_);
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, limit_);
    }
    if (logs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLogs());
    }
    if (snapshot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getSnapshot());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getError());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.proto.ReplicatorCommand)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.proto.ReplicatorCommand other = (com.github.ylgrgyq.proto.ReplicatorCommand) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && getTopic()
        .equals(other.getTopic());
    result = result && (getFromIndex()
        == other.getFromIndex());
    result = result && (getLimit()
        == other.getLimit());
    result = result && (hasLogs() == other.hasLogs());
    if (hasLogs()) {
      result = result && getLogs()
          .equals(other.getLogs());
    }
    result = result && (hasSnapshot() == other.hasSnapshot());
    if (hasSnapshot()) {
      result = result && getSnapshot()
          .equals(other.getSnapshot());
    }
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + FROMINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFromIndex());
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    if (hasLogs()) {
      hash = (37 * hash) + LOGS_FIELD_NUMBER;
      hash = (53 * hash) + getLogs().hashCode();
    }
    if (hasSnapshot()) {
      hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshot().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.ReplicatorCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.proto.ReplicatorCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.proto.ReplicatorCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.proto.ReplicatorCommand)
      com.github.ylgrgyq.proto.ReplicatorCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_ReplicatorCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_ReplicatorCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.proto.ReplicatorCommand.class, com.github.ylgrgyq.proto.ReplicatorCommand.Builder.class);
    }

    // Construct using com.github.ylgrgyq.proto.ReplicatorCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      topic_ = "";

      fromIndex_ = 0L;

      limit_ = 0;

      if (logsBuilder_ == null) {
        logs_ = null;
      } else {
        logs_ = null;
        logsBuilder_ = null;
      }
      if (snapshotBuilder_ == null) {
        snapshot_ = null;
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_ReplicatorCommand_descriptor;
    }

    public com.github.ylgrgyq.proto.ReplicatorCommand getDefaultInstanceForType() {
      return com.github.ylgrgyq.proto.ReplicatorCommand.getDefaultInstance();
    }

    public com.github.ylgrgyq.proto.ReplicatorCommand build() {
      com.github.ylgrgyq.proto.ReplicatorCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.proto.ReplicatorCommand buildPartial() {
      com.github.ylgrgyq.proto.ReplicatorCommand result = new com.github.ylgrgyq.proto.ReplicatorCommand(this);
      result.type_ = type_;
      result.topic_ = topic_;
      result.fromIndex_ = fromIndex_;
      result.limit_ = limit_;
      if (logsBuilder_ == null) {
        result.logs_ = logs_;
      } else {
        result.logs_ = logsBuilder_.build();
      }
      if (snapshotBuilder_ == null) {
        result.snapshot_ = snapshot_;
      } else {
        result.snapshot_ = snapshotBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.proto.ReplicatorCommand) {
        return mergeFrom((com.github.ylgrgyq.proto.ReplicatorCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.proto.ReplicatorCommand other) {
      if (other == com.github.ylgrgyq.proto.ReplicatorCommand.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (other.getFromIndex() != 0L) {
        setFromIndex(other.getFromIndex());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      if (other.hasLogs()) {
        mergeLogs(other.getLogs());
      }
      if (other.hasSnapshot()) {
        mergeSnapshot(other.getSnapshot());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.proto.ReplicatorCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.proto.ReplicatorCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
     */
    public com.github.ylgrgyq.proto.ReplicatorCommand.CommandType getType() {
      com.github.ylgrgyq.proto.ReplicatorCommand.CommandType result = com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.valueOf(type_);
      return result == null ? com.github.ylgrgyq.proto.ReplicatorCommand.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
     */
    public Builder setType(com.github.ylgrgyq.proto.ReplicatorCommand.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>optional string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private long fromIndex_ ;
    /**
     * <code>optional int64 fromIndex = 3;</code>
     */
    public long getFromIndex() {
      return fromIndex_;
    }
    /**
     * <code>optional int64 fromIndex = 3;</code>
     */
    public Builder setFromIndex(long value) {
      
      fromIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 fromIndex = 3;</code>
     */
    public Builder clearFromIndex() {
      
      fromIndex_ = 0L;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <code>optional int32 limit = 4;</code>
     */
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>optional int32 limit = 4;</code>
     */
    public Builder setLimit(int value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 limit = 4;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0;
      onChanged();
      return this;
    }

    private com.github.ylgrgyq.proto.SyncLogEntries logs_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.SyncLogEntries, com.github.ylgrgyq.proto.SyncLogEntries.Builder, com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder> logsBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public boolean hasLogs() {
      return logsBuilder_ != null || logs_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public com.github.ylgrgyq.proto.SyncLogEntries getLogs() {
      if (logsBuilder_ == null) {
        return logs_ == null ? com.github.ylgrgyq.proto.SyncLogEntries.getDefaultInstance() : logs_;
      } else {
        return logsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public Builder setLogs(com.github.ylgrgyq.proto.SyncLogEntries value) {
      if (logsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        logs_ = value;
        onChanged();
      } else {
        logsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public Builder setLogs(
        com.github.ylgrgyq.proto.SyncLogEntries.Builder builderForValue) {
      if (logsBuilder_ == null) {
        logs_ = builderForValue.build();
        onChanged();
      } else {
        logsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public Builder mergeLogs(com.github.ylgrgyq.proto.SyncLogEntries value) {
      if (logsBuilder_ == null) {
        if (logs_ != null) {
          logs_ =
            com.github.ylgrgyq.proto.SyncLogEntries.newBuilder(logs_).mergeFrom(value).buildPartial();
        } else {
          logs_ = value;
        }
        onChanged();
      } else {
        logsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public Builder clearLogs() {
      if (logsBuilder_ == null) {
        logs_ = null;
        onChanged();
      } else {
        logs_ = null;
        logsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public com.github.ylgrgyq.proto.SyncLogEntries.Builder getLogsBuilder() {
      
      onChanged();
      return getLogsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    public com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder getLogsOrBuilder() {
      if (logsBuilder_ != null) {
        return logsBuilder_.getMessageOrBuilder();
      } else {
        return logs_ == null ?
            com.github.ylgrgyq.proto.SyncLogEntries.getDefaultInstance() : logs_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.SyncLogEntries, com.github.ylgrgyq.proto.SyncLogEntries.Builder, com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder> 
        getLogsFieldBuilder() {
      if (logsBuilder_ == null) {
        logsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.proto.SyncLogEntries, com.github.ylgrgyq.proto.SyncLogEntries.Builder, com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder>(
                getLogs(),
                getParentForChildren(),
                isClean());
        logs_ = null;
      }
      return logsBuilder_;
    }

    private com.github.ylgrgyq.proto.Snapshot snapshot_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.Snapshot, com.github.ylgrgyq.proto.Snapshot.Builder, com.github.ylgrgyq.proto.SnapshotOrBuilder> snapshotBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public boolean hasSnapshot() {
      return snapshotBuilder_ != null || snapshot_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public com.github.ylgrgyq.proto.Snapshot getSnapshot() {
      if (snapshotBuilder_ == null) {
        return snapshot_ == null ? com.github.ylgrgyq.proto.Snapshot.getDefaultInstance() : snapshot_;
      } else {
        return snapshotBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public Builder setSnapshot(com.github.ylgrgyq.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snapshot_ = value;
        onChanged();
      } else {
        snapshotBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public Builder setSnapshot(
        com.github.ylgrgyq.proto.Snapshot.Builder builderForValue) {
      if (snapshotBuilder_ == null) {
        snapshot_ = builderForValue.build();
        onChanged();
      } else {
        snapshotBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public Builder mergeSnapshot(com.github.ylgrgyq.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (snapshot_ != null) {
          snapshot_ =
            com.github.ylgrgyq.proto.Snapshot.newBuilder(snapshot_).mergeFrom(value).buildPartial();
        } else {
          snapshot_ = value;
        }
        onChanged();
      } else {
        snapshotBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public Builder clearSnapshot() {
      if (snapshotBuilder_ == null) {
        snapshot_ = null;
        onChanged();
      } else {
        snapshot_ = null;
        snapshotBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public com.github.ylgrgyq.proto.Snapshot.Builder getSnapshotBuilder() {
      
      onChanged();
      return getSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    public com.github.ylgrgyq.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
      if (snapshotBuilder_ != null) {
        return snapshotBuilder_.getMessageOrBuilder();
      } else {
        return snapshot_ == null ?
            com.github.ylgrgyq.proto.Snapshot.getDefaultInstance() : snapshot_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.Snapshot, com.github.ylgrgyq.proto.Snapshot.Builder, com.github.ylgrgyq.proto.SnapshotOrBuilder> 
        getSnapshotFieldBuilder() {
      if (snapshotBuilder_ == null) {
        snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.proto.Snapshot, com.github.ylgrgyq.proto.Snapshot.Builder, com.github.ylgrgyq.proto.SnapshotOrBuilder>(
                getSnapshot(),
                getParentForChildren(),
                isClean());
        snapshot_ = null;
      }
      return snapshotBuilder_;
    }

    private com.github.ylgrgyq.proto.ErrorInfo error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.ErrorInfo, com.github.ylgrgyq.proto.ErrorInfo.Builder, com.github.ylgrgyq.proto.ErrorInfoOrBuilder> errorBuilder_;
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public com.github.ylgrgyq.proto.ErrorInfo getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.github.ylgrgyq.proto.ErrorInfo.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public Builder setError(com.github.ylgrgyq.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public Builder setError(
        com.github.ylgrgyq.proto.ErrorInfo.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public Builder mergeError(com.github.ylgrgyq.proto.ErrorInfo value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.github.ylgrgyq.proto.ErrorInfo.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public com.github.ylgrgyq.proto.ErrorInfo.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    public com.github.ylgrgyq.proto.ErrorInfoOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.github.ylgrgyq.proto.ErrorInfo.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ylgrgyq.proto.ErrorInfo, com.github.ylgrgyq.proto.ErrorInfo.Builder, com.github.ylgrgyq.proto.ErrorInfoOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ylgrgyq.proto.ErrorInfo, com.github.ylgrgyq.proto.ErrorInfo.Builder, com.github.ylgrgyq.proto.ErrorInfoOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.proto.ReplicatorCommand)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.proto.ReplicatorCommand)
  private static final com.github.ylgrgyq.proto.ReplicatorCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.proto.ReplicatorCommand();
  }

  public static com.github.ylgrgyq.proto.ReplicatorCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplicatorCommand>
      PARSER = new com.google.protobuf.AbstractParser<ReplicatorCommand>() {
    public ReplicatorCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReplicatorCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplicatorCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplicatorCommand> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.proto.ReplicatorCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

