// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.proto;

public interface ReplicatorCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.ylgrgyq.proto.ReplicatorCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .com.github.ylgrgyq.proto.ReplicatorCommand.CommandType type = 1;</code>
   */
  com.github.ylgrgyq.proto.ReplicatorCommand.CommandType getType();

  /**
   * <code>optional string topic = 2;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>optional string topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>optional int64 fromIndex = 3;</code>
   */
  long getFromIndex();

  /**
   * <code>optional int32 limit = 4;</code>
   */
  int getLimit();

  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  boolean hasLogs();
  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  com.github.ylgrgyq.proto.SyncLogEntries getLogs();
  /**
   * <code>optional .com.github.ylgrgyq.proto.SyncLogEntries logs = 5;</code>
   */
  com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder getLogsOrBuilder();

  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  boolean hasSnapshot();
  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  com.github.ylgrgyq.proto.Snapshot getSnapshot();
  /**
   * <code>optional .com.github.ylgrgyq.proto.Snapshot snapshot = 6;</code>
   */
  com.github.ylgrgyq.proto.SnapshotOrBuilder getSnapshotOrBuilder();

  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  boolean hasError();
  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  com.github.ylgrgyq.proto.ErrorInfo getError();
  /**
   * <code>optional .com.github.ylgrgyq.proto.ErrorInfo error = 7;</code>
   */
  com.github.ylgrgyq.proto.ErrorInfoOrBuilder getErrorOrBuilder();
}
