// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package com.github.ylgrgyq.proto;

/**
 * Protobuf type {@code com.github.ylgrgyq.proto.SyncLogEntries}
 */
public  final class SyncLogEntries extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.ylgrgyq.proto.SyncLogEntries)
    SyncLogEntriesOrBuilder {
  // Use SyncLogEntries.newBuilder() to construct.
  private SyncLogEntries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncLogEntries() {
    entries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SyncLogEntries(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              entries_ = new java.util.ArrayList<com.github.ylgrgyq.proto.LogEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            entries_.add(
                input.readMessage(com.github.ylgrgyq.proto.LogEntry.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        entries_ = java.util.Collections.unmodifiableList(entries_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_SyncLogEntries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ylgrgyq.proto.SyncLogEntries.class, com.github.ylgrgyq.proto.SyncLogEntries.Builder.class);
  }

  public static final int ENTRIES_FIELD_NUMBER = 1;
  private java.util.List<com.github.ylgrgyq.proto.LogEntry> entries_;
  /**
   * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
   */
  public java.util.List<com.github.ylgrgyq.proto.LogEntry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
   */
  public java.util.List<? extends com.github.ylgrgyq.proto.LogEntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
   */
  public com.github.ylgrgyq.proto.LogEntry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
   */
  public com.github.ylgrgyq.proto.LogEntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(1, entries_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entries_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ylgrgyq.proto.SyncLogEntries)) {
      return super.equals(obj);
    }
    com.github.ylgrgyq.proto.SyncLogEntries other = (com.github.ylgrgyq.proto.SyncLogEntries) obj;

    boolean result = true;
    result = result && getEntriesList()
        .equals(other.getEntriesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ylgrgyq.proto.SyncLogEntries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ylgrgyq.proto.SyncLogEntries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.ylgrgyq.proto.SyncLogEntries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.ylgrgyq.proto.SyncLogEntries)
      com.github.ylgrgyq.proto.SyncLogEntriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_SyncLogEntries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ylgrgyq.proto.SyncLogEntries.class, com.github.ylgrgyq.proto.SyncLogEntries.Builder.class);
    }

    // Construct using com.github.ylgrgyq.proto.SyncLogEntries.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntriesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ylgrgyq.proto.Commands.internal_static_com_github_ylgrgyq_proto_SyncLogEntries_descriptor;
    }

    public com.github.ylgrgyq.proto.SyncLogEntries getDefaultInstanceForType() {
      return com.github.ylgrgyq.proto.SyncLogEntries.getDefaultInstance();
    }

    public com.github.ylgrgyq.proto.SyncLogEntries build() {
      com.github.ylgrgyq.proto.SyncLogEntries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.ylgrgyq.proto.SyncLogEntries buildPartial() {
      com.github.ylgrgyq.proto.SyncLogEntries result = new com.github.ylgrgyq.proto.SyncLogEntries(this);
      int from_bitField0_ = bitField0_;
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ylgrgyq.proto.SyncLogEntries) {
        return mergeFrom((com.github.ylgrgyq.proto.SyncLogEntries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ylgrgyq.proto.SyncLogEntries other) {
      if (other == com.github.ylgrgyq.proto.SyncLogEntries.getDefaultInstance()) return this;
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ylgrgyq.proto.SyncLogEntries parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ylgrgyq.proto.SyncLogEntries) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.ylgrgyq.proto.LogEntry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        entries_ = new java.util.ArrayList<com.github.ylgrgyq.proto.LogEntry>(entries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ylgrgyq.proto.LogEntry, com.github.ylgrgyq.proto.LogEntry.Builder, com.github.ylgrgyq.proto.LogEntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public java.util.List<com.github.ylgrgyq.proto.LogEntry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public com.github.ylgrgyq.proto.LogEntry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder setEntries(
        int index, com.github.ylgrgyq.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder setEntries(
        int index, com.github.ylgrgyq.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder addEntries(com.github.ylgrgyq.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder addEntries(
        int index, com.github.ylgrgyq.proto.LogEntry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder addEntries(
        com.github.ylgrgyq.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder addEntries(
        int index, com.github.ylgrgyq.proto.LogEntry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends com.github.ylgrgyq.proto.LogEntry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public com.github.ylgrgyq.proto.LogEntry.Builder getEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public com.github.ylgrgyq.proto.LogEntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public java.util.List<? extends com.github.ylgrgyq.proto.LogEntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public com.github.ylgrgyq.proto.LogEntry.Builder addEntriesBuilder() {
      return getEntriesFieldBuilder().addBuilder(
          com.github.ylgrgyq.proto.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public com.github.ylgrgyq.proto.LogEntry.Builder addEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().addBuilder(
          index, com.github.ylgrgyq.proto.LogEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.ylgrgyq.proto.LogEntry entries = 1;</code>
     */
    public java.util.List<com.github.ylgrgyq.proto.LogEntry.Builder> 
         getEntriesBuilderList() {
      return getEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ylgrgyq.proto.LogEntry, com.github.ylgrgyq.proto.LogEntry.Builder, com.github.ylgrgyq.proto.LogEntryOrBuilder> 
        getEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ylgrgyq.proto.LogEntry, com.github.ylgrgyq.proto.LogEntry.Builder, com.github.ylgrgyq.proto.LogEntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.github.ylgrgyq.proto.SyncLogEntries)
  }

  // @@protoc_insertion_point(class_scope:com.github.ylgrgyq.proto.SyncLogEntries)
  private static final com.github.ylgrgyq.proto.SyncLogEntries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ylgrgyq.proto.SyncLogEntries();
  }

  public static com.github.ylgrgyq.proto.SyncLogEntries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncLogEntries>
      PARSER = new com.google.protobuf.AbstractParser<SyncLogEntries>() {
    public SyncLogEntries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncLogEntries(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncLogEntries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncLogEntries> getParserForType() {
    return PARSER;
  }

  public com.github.ylgrgyq.proto.SyncLogEntries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

