[package]
name = "bear_reader"
version = "0.1.0"
authors = ["ylgrgyq <gr@ylgrgyq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.18.0"
strum_macros="0.18.0"
clap = "2.33.1"
rusqlite = "0.23.1"